# Generated by Django 4.2.6 on 2023-12-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_authuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
    ]
